export const INDUSTRIES = [
  "Plumbing",
  "HVAC",
  "Electrical",
  "Roofing",
  "Landscaping",
  "Pest Control",
  "Auto Repair",
  "Dentist",
  "Chiropractor",
  "Med Spa",
  "Law Firm",
  "Accounting",
  "Real Estate",
  "Restaurant",
  "Coffee Shop",
  "Bakery",
  "Gym",
  "Salon",
  "Tattoo Studio",
  "Photography",
  "Event Planner",
  "Catering",
  "Moving Company",
  "Cleaning Service",
  "Locksmith",
  "Self Storage",
  "Auto Dealer",
  "Car Wash",
  "Hotel",
  "Bed And Breakfast",
  "Campground",
  "Marina",
  "RV Park",
  "Tour Operator",
  "Boutique",
  "Florist",
  "Pharmacy",
  "Optometrist",
  "Veterinarian",
  "Pet Groomer",
  "Daycare",
  "Tutoring",
  "Music School",
  "Driving School",
  "Farm",
  "Ranch",
  "Vineyard",
  "Brewery",
];

export const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS",
  "KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY",
  "NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
];
